language: java

jdk:
    - oraclejdk7
#    - oraclejdk8

cache:
    directories:
        - $HOME/.wine
        - $HOME/.jdk_cache
        - $HOME/.m2

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y wine1.6
    - ./scripts/setup-wine.sh

script:
    - ./scripts/test.sh
#
#after_success:
#    - ./scripts/deploy-snapshot.sh
#
#env:
#    global:
#        - secure: "AnsdYjHIvtLXrDMJmlf5FJhXJOW+aLSvsyXcGFLKse6EcwTSw8XnE4bGv2eSi2YWIwoHHCStIQbI0J02rkmUu9Z5oChxhOyGtCd8U4l1XciH2U7vJOJ/i9Auw5WgLM6x8HxgH6myhNrA9xrB4fcH+8WsDMf+qLqgvJQQjqQZQGM="
#        - secure: "tKWNiNnT+WPmHNY1MtXTgwId9peXtsKQ5owdOfZqmEQYTSHVdya5Bt3CiK8U829Pa1ZBuF+9mnGufTbw0WfQM5TKlClDn4ciEJzz6ChS2cqO+6trsWy335nppU7pQsDE44Irju+E7Jh4kIjfnB2pWRhI2YAoAUhNyz39PawXsz8="

