language: java

jdk:
    - oraclejdk7
#    - oraclejdk8

addons:
  apt:
  #  sources:
    #- ubuntu-wine
    packages:
    - wine

cache:
  directories:
#        - $HOME/.wine
        - $HOME/.jdk_cache
        - $HOME/.m2

before_install:
    - ./scripts/setup-wine.sh

script:
    - ./scripts/test.sh
